#!/usr/bin/env python3
"""
Generate GitHub issue reports with tracking tables (Big Model Radar format).

Reads weekly data snapshots and creates formatted GitHub issues.
"""

import json
import os
import sys
from datetime import datetime
import glob


def format_markdown_table(weekly_data):
    """Format weekly security tracking as markdown table."""
    repos = weekly_data.get("repositories", {})

    if not repos:
        return "No security issues found this week."

    # Sort by issue count (descending)
    sorted_repos = sorted(
        repos.items(),
        key=lambda x: x[1].get("issue_count", 0),
        reverse=True
    )

    # Build table
    lines = []
    lines.append("| Repository | Issues | Open | Closed | Top Issue | Link |")
    lines.append("|---|---|---|---|---|---|")

    for repo_name, data in sorted_repos:
        issue_count = data.get("issue_count", 0)
        open_count = data.get("open_count", 0)
        closed_count = data.get("closed_count", 0)

        top_issue = data.get("top_issues", [{}])[0]
        issue_title = top_issue.get("title", "No issues") if top_issue else "No issues"
        issue_link = top_issue.get("url", "#") if top_issue else "#"
        issue_num = top_issue.get("number", "") if top_issue else ""

        # Truncate title if too long
        if len(issue_title) > 40:
            issue_title = issue_title[:37] + "..."

        trend = "↑" if open_count > 0 else "→"

        repo_link = f"https://github.com/{data.get('owner')}/{data.get('repo')}"
        lines.append(
            f"| [{repo_name}]({repo_link}) | {issue_count} | {open_count} | {closed_count} | "
            f"[#{issue_num}]({issue_link}) {issue_title} | [→]({repo_link}/issues) |"
        )

    return "\n".join(lines)


def create_issue_body(weekly_data):
    """Create complete markdown body for GitHub issue."""
    week = weekly_data.get("week", "Unknown")
    start_date = weekly_data.get("start_date", "")
    end_date = weekly_data.get("end_date", "")
    repos_tracked = weekly_data.get("repos_tracked", 0)
    total_issues = sum(
        r.get("issue_count", 0)
        for r in weekly_data.get("repositories", {}).values()
    )

    open_issues = sum(
        r.get("open_count", 0)
        for r in weekly_data.get("repositories", {}).values()
    )

    lines = []

    # Header
    lines.append(f"# AI Security Tracker — Week {week}")
    lines.append("")
    lines.append(f"**Period:** {start_date.split('T')[0]} to {end_date.split('T')[0]}")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append(f"- **Repos Tracked:** {repos_tracked}")
    lines.append(f"- **Total Security Issues:** {total_issues}")
    lines.append(f"- **Open Issues:** {open_issues}")
    lines.append(f"- **Closed Issues:** {total_issues - open_issues}")
    lines.append("")

    # Security Issues Table
    lines.append("## Security Issues by Repository")
    lines.append("")
    lines.append(format_markdown_table(weekly_data))
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Generated by [AI Security Tracker](https://github.com/ppradyoth/ai-security-tracker) — Comprehensive ecosystem security monitoring*")
    lines.append("")
    lines.append(f"*Last updated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}*")

    return "\n".join(lines)


def main():
    """Main entry point."""
    # Find all weekly JSON files
    weekly_files = sorted(glob.glob("data/week-*.json"))

    if not weekly_files:
        sys.stderr.write("No weekly data files found. Run backfill first.\n")
        sys.exit(1)

    sys.stderr.write(f"Found {len(weekly_files)} weekly snapshots\n\n")

    # Create issues directory for archival
    os.makedirs("issues", exist_ok=True)

    # Process each week
    for weekly_file in weekly_files:
        try:
            with open(weekly_file, "r") as f:
                weekly_data = json.load(f)
        except Exception as e:
            sys.stderr.write(f"Error reading {weekly_file}: {e}\n")
            continue

        week = weekly_data.get("week", "unknown")
        sys.stderr.write(f"Processing week {week}... ")

        # Create markdown report
        body = create_issue_body(weekly_data)

        # Save to file (can be posted to GitHub issues)
        issue_title = f"[Tracking] {week} — AI Security Ecosystem Report"
        issue_file = f"issues/{week}-report.md"

        # Save as markdown
        with open(issue_file, "w") as f:
            f.write(f"# {issue_title}\n\n")
            f.write(body)

        sys.stderr.write(f"created {issue_file}\n")

    sys.stderr.write(f"\n✅ Issue reports generated\n")
    sys.stderr.write(f"Files saved in issues/ directory\n")
    sys.stderr.write(f"Next: Post these to GitHub issues for historical tracking\n")


if __name__ == "__main__":
    main()
